const scenes=[];let paused=matchMedia('(prefers-reduced-motion: reduce)').matches;let elapsed=0,last=0,paintAt=0;
const gallery=document.querySelector('#gallery');
Object.entries(MopixyScenes.definitions).forEach(([id,d])=>{const card=document.createElement('article');card.className='gallery-card';card.innerHTML=`<button class="gallery-phone-button" data-select="${id}" aria-label="Try ${d.title}"><div class="phone" data-scene="${id}"><div class="phone-screen"><canvas width="384" height="682" aria-label="${d.title} animated wallpaper"></canvas><div class="phone-ui"><span class="phone-date">Wednesday, October 7</span><span class="phone-clock">09:41</span></div><span class="home-bar"></span></div></div></button><span class="gallery-category">${d.category}</span><h3>${d.title}</h3><p>${d.description}</p>`;gallery.append(card)});
document.querySelectorAll('.phone').forEach(phone=>{const scene=new MopixyScenes.Scene(phone.querySelector('canvas'),phone.dataset.scene);scenes.push(scene);phone.scene=scene});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.scene.visible=e.isIntersecting),{rootMargin:'80px'});document.querySelectorAll('.phone').forEach(p=>observer.observe(p));
MopixyScenes.ready.then(()=>scenes.forEach(s=>s.draw(0)));
function frame(now){const dt=last?Math.min((now-last)/1000,.1):0;last=now;if(!paused&&!document.hidden)elapsed+=dt;scenes.forEach(s=>{if(s.independent&&s.visible&&!document.hidden&&!s.localPaused)s.localElapsed=(s.localElapsed||0)+dt});if(now-paintAt>=83){scenes.forEach(s=>{if(s.visible&&!document.hidden&&((s.independent?!s.localPaused:!paused)||s.dirty))s.draw(s.independent?(s.localElapsed||0):elapsed)});paintAt=now}requestAnimationFrame(frame)}requestAnimationFrame(frame);
const main=document.querySelector('#main-phone');
document.querySelectorAll('.lock-symbol').forEach(el=>{el.setAttribute('aria-hidden','true');el.innerHTML='<svg width="12" height="14" viewBox="0 0 12 14" fill="none" aria-hidden="true"><path d="M3 6V4a3 3 0 0 1 6 0v2" stroke="currentColor" stroke-width="1.4"/><rect x="1.5" y="6" width="9" height="7" rx="2" stroke="currentColor" stroke-width="1.4"/></svg>'});
function select(id){main.dataset.scene=id;main.scene.id=id;main.scene.draw(elapsed);main.classList.remove('turning');void main.offsetWidth;main.classList.add('turning');main.querySelector('canvas').setAttribute('aria-label',MopixyScenes.definitions[id].title+' animated wallpaper');document.querySelector('#scene-title').textContent=MopixyScenes.definitions[id].title;main.querySelector('.phone-weather').textContent={snow:'A little snow. A little quiet.',chime:'Let the afternoon linger.',console:'A tiny adventure awaits.',soda:'Take the slow afternoon.',lantern:'A warm light to come home to.'}[id];document.querySelectorAll('.scene-picker button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.select===id));document.querySelector('#snow-control').hidden=id!=='snow'}
main.addEventListener('animationend',e=>{if(e.animationName==='phone-turn')main.classList.remove('turning')});
const pixelM=['110000011','111000111','111101111','110111011','110010011','110000011','110000011'];
const mSvg='<svg class="pixel-m" viewBox="0 0 9 7" fill="currentColor" aria-hidden="true" shape-rendering="crispEdges">'+pixelM.map((row,y)=>[...row].map((cell,x)=>cell==='1'?`<rect x="${x}" y="${y}" width="1" height="1"/>`:'').join('')).join('')+'</svg>';
document.querySelectorAll('.brand').forEach(brand=>{brand.setAttribute('aria-label','Mopixy home');const word=document.createElement('span');word.className='brand-word';word.setAttribute('aria-hidden','true');word.innerHTML=mSvg+'<span>OPIXY</span>';if(brand.querySelector('img'))brand.querySelector('span').replaceWith(word);else brand.replaceChildren(word)});
document.querySelectorAll('[data-select]').forEach(button=>button.addEventListener('click',()=>{select(button.dataset.select);if(button.classList.contains('gallery-phone-button'))document.querySelector('.preview-controls').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'end'})}));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{main.classList.remove('home','art');if(b.dataset.view!=='lock')main.classList.add(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',x===b));main.querySelector('.home-ui').setAttribute('aria-hidden',b.dataset.view!=='home')}));
const toggle=document.querySelector('#motion-toggle');function updateMotion(){toggle.setAttribute('aria-pressed',paused);toggle.textContent=paused?'Play wallpaper':'Pause wallpaper'}updateMotion();toggle.addEventListener('click',()=>{paused=!paused;updateMotion()});
document.querySelector('#night-toggle').addEventListener('change',e=>{main.scene.night=e.target.checked;main.scene.draw(elapsed)});
document.querySelector('#snow-phase').addEventListener('input',e=>{main.scene.snowPhase=Number(e.target.value);main.scene.snowDeposits.fill(0);if(main.scene.branchDeposits)main.scene.branchDeposits.forEach(row=>row.fill(0));const s=main.scene.snowPhase;document.querySelector('#snow-label').textContent=s===0?'Fresh snowfall':s<10800?'Snowfall':s<12420?'Deep snow':s<19440?'Sunny thaw':'Clear sky';main.scene.draw(elapsed)});
document.querySelectorAll('.mascot-button').forEach(b=>b.addEventListener('click',()=>{b.classList.remove('jumping');void b.offsetWidth;b.classList.add('jumping');b.querySelectorAll('.burst-pixel').forEach(p=>p.remove());for(let i=0;i<16;i++){const p=document.createElement('i');p.className='burst-pixel';const angle=(i/16)*Math.PI*2;p.style.setProperty('--dx',Math.cos(angle)*(45+i%4*12)+'px');p.style.setProperty('--dy',Math.sin(angle)*55-30+'px');b.append(p);setTimeout(()=>p.remove(),1000)}}));
setTimeout(()=>{if(!matchMedia('(prefers-reduced-motion: reduce)').matches)document.querySelector('.mascot-button').click()},700);
document.addEventListener('visibilitychange',()=>{last=0});
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{paused=e.matches;updateMotion();scenes.forEach(s=>s.dirty=true)});
const brightness=document.querySelector('#brightness'),zoom=document.querySelector('#crop-zoom'),cropY=document.querySelector('#crop-y'),motionLevel=document.querySelector('#motion-level');
function applyLook(){main.scene.brightness=Number(brightness.value)/100;main.scene.zoom=Number(zoom.value)/100;main.scene.cropY=Number(cropY.value)/100;main.scene.speed=Number(motionLevel.value);document.querySelector('#brightness-value').textContent=brightness.value+'%';document.querySelector('#crop-value').textContent=zoom.value+'%';main.scene.draw(elapsed)}
[brightness,zoom,cropY,motionLevel].forEach(input=>input.addEventListener('input',applyLook));document.querySelector('#reset-look').addEventListener('click',()=>{brightness.value=zoom.value=100;cropY.value=0;motionLevel.value=1;document.querySelector('#night-toggle').checked=false;main.scene.night=false;applyLook()});
// Public read-only diagnostics for local verification.
window.mopixyDemo={scenes,get paused(){return paused},select};
// A local preview needs to refresh its running JavaScript, not only its source files.
if(['localhost','127.0.0.1'].includes(location.hostname)){
  let previewVersion;
  setInterval(async()=>{if(document.hidden)return;try{const r=await fetch('/__preview-version',{cache:'no-store'});if(!r.ok)return;const value=await r.text();if(previewVersion&&value!==previewVersion)location.reload();previewVersion=value}catch{}},1500);
}

